src/lighthouse/Lighthouse.ts, src/lighthouse/__tests__/Lighthouse.spec.ts
1) https://maddevs.atlassian.net/browse/MAR-2078
2) Added a try catch error handler so that when an error occurs in the request, the application does not break
3) Updated the getData method tests for catching errors from lighthouse.
4) Added a check for the buildAverageResult function so that it does not return NAN
=> MAR-2145  Added a try catch error handler so that when an error occurs in the request, the application does not break

src/blocks/Blocks.ts
1) https://maddevs.atlassian.net/browse/MAR-1719
2)  Added Emoji rate, corrected text
3)
=> MAR-2160 Added Emoji rate

package.json
Debug  semantic-release and push npm
=> fix: MAR-2362 debug semantic-release

README.md, src/lighthouse/Lighthouse.ts, src/lighthouse/Sitemap.ts, src/lighthouse/__tests__/Lighthouse.spec.ts, src/lighthouse/__tests__/Sitemap.spec.ts, src/lighthouse/interfaces/LighthouseParams.ts
Corrected lighthouse config
Corrected lighthouse tests
Updated Readme
=> MAR-1768 Updated Readme

README.md
1) https://maddevs.atlassian.net/browse/MAR-2571
2) Updated readme
=> MAR-2571 Updated readme

package.json, src/Radiator.ts, src/__tests__/Radiator.spec.ts, src/__tests__/fixtures/defaultRadiatorConfigs.ts, src/interfaces/RadiatorConfig.ts, src/messengers/MessageBuilder.ts, src/messengers/__tests__/MessengerService.spec.ts, src/utils/__tests__/parseRange.spec.ts, src/utils/parseRange.ts, yarn.lock
1) https://maddevs.atlassian.net/browse/MAR-1762
2) Added the ability to configure the time zone
=> MAR-1762 Added the ability to configure the time zone

src/lighthouse/Sitemap.ts
the task: https://maddevs.atlassian.net/browse/MAR-2742
1. Added logic to delete a slash from end of URL
=> MAR-2742. Added logic to delete a slash from end of URL

package.json
the task: https://maddevs.atlassian.net/browse/MAR-2780
1. Updated package version
=> MAR-2780. Updated package

package.json, src/Radiator.ts, src/analytics/AnalyticsService.ts, src/authorization/GoogleAuthorization.ts, src/chartBuilder/ChartBuilder.ts, src/storage/GoogleDriveStorage.ts
the task: https://maddevs.atlassian.net/browse/MAR-2821
1. Updated version of the package and bugs fixed
=> MAR-2821. Updated version of the package and bugs fixed

example/index.js, src/Radiator.ts, src/__tests__/fixtures/defaultAnalyticsParams.ts, src/analytics/__tests__/ChartRepository.spec.ts, src/chartBuilder/ChartBuilder.ts, src/chartBuilder/__tests__/ChartBuilder.spec.ts, src/interfaces/ChartConfig.ts
the task: https://maddevs.atlassian.net/browse/MAR-3032
1. Added chartView parameter to show the chart in several views
2. Fixed tests
=> MAR-3032. Added chartView parameter to show the chart in several views

README.md, package.json, src/analytics/BlogsRepository.ts, src/chartBuilder/ChartBuilder.ts, src/messengers/MessageBuilder.ts
the task: https://maddevs.atlassian.net/browse/MAR-3146
=> MAR-3146. Added a slash check at the end of the url

src/__tests__/fixtures/defaultLighthouseParams.ts, src/lighthouse/Sitemap.ts, src/lighthouse/interfaces/LighthouseParams.ts
the task: https://maddevs.atlassian.net/browse/MAR-3476
1. Deleted sitemapUrl option
2. Fixed tests
=> MAR-3476. Deleted sitemapUrl option

example/index.html, example/index.js, jest.config.js, src/Radiator.ts, src/analytics/CoreRepository.ts, src/analytics/__tests__/CoreRepository.spec.ts, src/messengers/MessageBuilder.ts, src/messengers/interfaces/BuildMessageData.ts, src/pagesAnalytics/NewPagesInSite.ts, src/pagesAnalytics/PageAnalytics.ts, src/pagesAnalytics/index.ts, src/pagesAnalytics/interfaces/Pages.ts, src/pagesAnalytics/interfaces/index.ts, src/sitemap/Sitemap.ts, src/sitemap/index.ts, src/sitemap/interfaces/SitemapOptions.ts, src/sitemap/interfaces/index.ts, src/utils/firestore.ts, src/utils/getFirstDayOfCurrentMonth.ts, src/utils/getMonthName.ts
1. [Выводить количество новых страниц на сайте](https://maddevs.atlassian.net/browse/MAR-3471)
2. Merge with roman/firestore. Resolved conflicts.
Added goals for new pages from our site.
=> MAR-3471. Added goals for new pages from our site.

example/index.js, src/Radiator.ts, src/analytics/BlogsRepository.ts, src/quora/QuoraService.ts, src/quora/__test__/index.spec.ts, src/quora/interfaces/FirestoreData.ts, src/quora/interfaces/QuoraParams.ts, src/quora/interfaces/index.ts
the task: https://maddevs.atlassian.net/browse/MAR-3563
1. Added filter to the Quora metric
=> MAR-3563. Added filter to the Quora metric

example/index.js, src/Radiator.ts, src/interfaces/RadiatorConfig.ts, src/utils/parseRange.ts
1. [MAR-3727: Изменить дату отправки радиатора и переделать работу с firestore](https://maddevs.atlassian.net/browse/MAR-3727)
2. Fixed date for production.
=> MAR-3727. Fixed date for production.

src/Radiator.ts, src/__tests__/fixtures/defaultAnalyticsParams.ts, src/analytics/interfaces/analytics.interfaces.ts, src/chartBuilder/__tests__/ChartBuilder.spec.ts, src/enji/EnjiService.ts, src/enji/index.ts
the task: https://maddevs.atlassian.net/browse/MAR-3713
1. Add the logic to send total users to the enji endpoint
=> MAR-3713. Add the logic to send total users to the enji endpoint

src/Radiator.ts, src/analytics/interfaces/analytics.interfaces.ts
1. Temporary comment the Enji service
=> MAR-3743. fix: commented enji service

example/index.js, package.json, src/Radiator.ts, src/__tests__/Radiator.spec.ts, src/__tests__/fixtures/parsedRange.ts, src/enji/EnjiService.ts, src/glassdoor/GlassdoorService.ts, src/interfaces/Range.ts, src/utils/__tests__/parseRange.spec.ts, src/utils/parseRange.ts
the task: https://maddevs.atlassian.net/browse/MAR-3713
1. Refactore enji service logic
2. Chage types
=> MAR-3743-refactore enji service

package.json, src/Radiator.ts, src/__tests__/Radiator.spec.ts, src/enji/EnjiService.ts, src/glassdoor/GlassdoorService.ts, src/utils/__tests__/parseRange.spec.ts, src/utils/parseRange.ts
the task: https://maddevs.atlassian.net/browse/MAR-3819
=> MAR-3819: add logging to the moment functions

src/glassdoor/GlassdoorService.ts
the task: https://maddevs.atlassian.net/browse/MAR-3472
1. Add logs to function which gets data from glassdoor
=> MAR-3472. Add logs to function which gets data from glassdoor

jest.config.js, package.json, src/__tests__/fixtures/parsedRange.ts, src/enji/__tests__/EnjiService.spec.ts, src/glassdoor/GlassdoorService.ts, src/glassdoor/__test__/index.spec.ts, src/glassdoor/interfaces/GlassdoorParams.ts, src/interfaces/Range.ts, src/utils/__tests__/parseRange.spec.ts, src/utils/parseRange.ts
the task: https://maddevs.atlassian.net/browse/MAR-3472
1. Refactor the logic to get reviews from glassdoor (use the external https://www.page2api.com/ service)
=> MAR-3472. Refactor the logic to get reviews from glassdoor

example/index.js, package.json, src/Radiator.ts, src/__tests__/Radiator.spec.ts, src/enji/__tests__/EnjiService.spec.ts, src/errors/types/SearchConsoleError.ts, src/messengers/MessageBuilder.ts, src/messengers/interfaces/BuildMessageData.ts, src/searchConsole/SearchConsole.ts, src/searchConsole/interfaces/ISearchConsoleAuthConfig.ts, src/searchConsole/interfaces/ISearchConsoleData.ts, src/searchConsole/interfaces/index.ts, yarn.lock
1. [MAR-3601: Метрика: search console](https://maddevs.atlassian.net/browse/MAR-3601)
2. Added sitemap search console metric.
Fixed tests and return imageUrl.
Fixed tests.
=> MAR-3601. Added sitemap search console metric.

README.md
the task: https://maddevs.atlassian.net/browse/MAR-3660
1. Update Readme file
=> MAR-3660: Update Readme

src/analytics/EbookDownloadsRepository.ts, src/messengers/MessageBuilder.ts, src/messengers/__tests__/SlackMessageBuilder.spec.ts
1. [MAR-4043: Изменить показатели по целям в маркетинговом радиаторе](https://maddevs.atlassian.net/browse/MAR-4043)
2. Added new ebook metric.
=> MAR-4043. Added new ebook metric.

src/quora/QuoraService.ts
1) [Обновить метрику "Количество новых постов на Quora"](https://maddevs.atlassian.net/browse/MAR-4207)
2) Commits: [Added quora answers count to report](https://github.com/maddevsio/mad-radiator/pull/90/commits/049098c83c382604fb9cb678dc65f9b9377c6f68)
=> MAR-4207. Added quora answers count to report

package.json, src/messengers/MessageBuilder.ts, src/messengers/__tests__/SlackMessageBuilder.spec.ts
1. [MAR-5026: Изменить цель по трафику в маркетинговом радиаторе](https://maddevs.atlassian.net/browse/MAR-5026)
2. [Added new users goals.](https://github.com/maddevsio/mad-radiator/commit/ef47f2dbcee6c6bb523753a4f3bd11a9ca0ec828)
=> MAR-5026. Added new users goals.

package.json, src/pagesAnalytics/PageAnalyticsService.ts, src/prismic/PrismicService.ts, src/prismic/interfaces/IPrismicService.ts, src/prismic/interfaces/index.ts, yarn.lock
1. [MAR-6402: Исправить показатели радиатора по кол-ву новых статей.](https://maddevs.atlassian.net/browse/MAR-6402)
2. Commits:
[Fix blog posts count.](https://github.com/maddevsio/mad-radiator/commit/bb76d52df7620b9eacff8de8c97e905c2fdbc3b6)
[Change package version.](https://github.com/maddevsio/mad-radiator/commit/66f80485ecb01122218a294c3c53d9d51e9fefa8)
=> MAR-6402. Fix blog posts count.
